"""initial tables

Revision ID: 00e9ddbb08bb
Revises: 
Create Date: 2026-03-10 15:39:59.652964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e9ddbb08bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_created_at'), 'admin_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('base_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('where_from', sa.String(length=50), nullable=False),
    sa.Column('kw', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.String(length=150), nullable=True),
    sa.Column('event_type', sa.String(length=150), nullable=True),
    sa.Column('event_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Pending', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_leads_created_at'), 'base_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_base_leads_email'), 'base_leads', ['email'], unique=False)
    op.create_index(op.f('ix_base_leads_id'), 'base_leads', ['id'], unique=False)
    op.create_index(op.f('ix_base_leads_name'), 'base_leads', ['name'], unique=False)
    op.create_index(op.f('ix_base_leads_phone'), 'base_leads', ['phone'], unique=False)
    op.create_index(op.f('ix_base_leads_service'), 'base_leads', ['service'], unique=False)
    op.create_index(op.f('ix_base_leads_status'), 'base_leads', ['status'], unique=False)
    op.create_index(op.f('ix_base_leads_where_from'), 'base_leads', ['where_from'], unique=False)
    op.create_table('combined_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('kw', sa.String(length=50), nullable=True),
    sa.Column('solar_budget', sa.String(length=150), nullable=True),
    sa.Column('event_type', sa.String(length=150), nullable=True),
    sa.Column('mandap_budget', sa.String(length=150), nullable=True),
    sa.Column('event_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['base_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combined_requests_lead_id'), 'combined_requests', ['lead_id'], unique=False)
    op.create_table('mandap_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=150), nullable=True),
    sa.Column('budget', sa.String(length=150), nullable=True),
    sa.Column('event_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['base_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandap_requests_lead_id'), 'mandap_requests', ['lead_id'], unique=False)
    op.create_table('solar_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('kw', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['base_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_requests_lead_id'), 'solar_requests', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_requests_lead_id'), table_name='solar_requests')
    op.drop_table('solar_requests')
    op.drop_index(op.f('ix_mandap_requests_lead_id'), table_name='mandap_requests')
    op.drop_table('mandap_requests')
    op.drop_index(op.f('ix_combined_requests_lead_id'), table_name='combined_requests')
    op.drop_table('combined_requests')
    op.drop_index(op.f('ix_base_leads_where_from'), table_name='base_leads')
    op.drop_index(op.f('ix_base_leads_status'), table_name='base_leads')
    op.drop_index(op.f('ix_base_leads_service'), table_name='base_leads')
    op.drop_index(op.f('ix_base_leads_phone'), table_name='base_leads')
    op.drop_index(op.f('ix_base_leads_name'), table_name='base_leads')
    op.drop_index(op.f('ix_base_leads_id'), table_name='base_leads')
    op.drop_index(op.f('ix_base_leads_email'), table_name='base_leads')
    op.drop_index(op.f('ix_base_leads_created_at'), table_name='base_leads')
    op.drop_table('base_leads')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_created_at'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
