"""initial_schema

Revision ID: 359946b55d30
Revises:
Create Date: 2025-12-07 14:20:44.023072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "359946b55d30"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_admin_users_id"), "admin_users", ["id"], unique=False)
    op.create_table(
        "base_leads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("service", sa.String(length=50), nullable=False),
        sa.Column("where_from", sa.String(length=50), nullable=False),
        sa.Column("kw", sa.String(length=50), nullable=True),
        sa.Column("budget", sa.String(length=150), nullable=True),
        sa.Column("event_type", sa.String(length=150), nullable=True),
        sa.Column("event_date", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_base_leads_id"), "base_leads", ["id"], unique=False)
    op.create_table(
        "combined_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("kw", sa.String(length=50), nullable=True),
        sa.Column("solar_budget", sa.String(length=150), nullable=True),
        sa.Column("event_type", sa.String(length=150), nullable=True),
        sa.Column("mandap_budget", sa.String(length=150), nullable=True),
        sa.Column("event_date", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["base_leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mandap_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=150), nullable=True),
        sa.Column("budget", sa.String(length=150), nullable=True),
        sa.Column("event_date", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["base_leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "solar_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("kw", sa.String(length=50), nullable=True),
        sa.Column("budget", sa.String(length=150), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["base_leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("solar_requests")
    op.drop_table("mandap_requests")
    op.drop_table("combined_requests")
    op.drop_index(op.f("ix_base_leads_id"), table_name="base_leads")
    op.drop_table("base_leads")
    op.drop_index(op.f("ix_admin_users_id"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
