"""add is_active column

Revision ID: fa2addbd1131
Revises: 00e9ddbb08bb
Create Date: 2026-03-12 23:14:45.769757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2addbd1131'
down_revision: Union[str, Sequence[str], None] = '00e9ddbb08bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('is_active', sa.String(length=10), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'is_active')
    # ### end Alembic commands ###
